/**
 * Curated re-exports of dashboard API types.
 *
 * The full path/operation surface is at `./api.generated.ts`, regenerated by
 * `npm run gen:api-types` against the live FastAPI OpenAPI document. This
 * file keeps the names short and is the only thing app code should import.
 *
 * A small handful of shapes (camera details, camera/plug registry blocks)
 * are augmented here directly. They mirror the Pydantic models added in
 * `lab_skills/registry.py` and `kasa_tapo_services/models.py` and become
 * the source of truth for the frontend until the next time
 * `npm run gen:api-types` is run.
 */

import type { components } from "./api.generated";

type Schemas = components["schemas"];

// Equipment kind: regenerate the OpenAPI types after adding `camera`,
// `smart_plug`, `power_strip` to lab_skills/models.py to drop this widen.
export type EquipmentKind =
  | NonNullable<Schemas["EquipmentSnapshot"]["kind"]>
  | "camera"
  | "smart_plug"
  | "power_strip";

export type EquipmentState = Schemas["EquipmentStatus"]["equipment_status"];
export type ErrorSeverity = Schemas["ErrorInfo"]["severity"];
export type FetchErrorKind = Schemas["FetchError"]["kind"];

export type ComponentStatus = Schemas["ComponentStatus"];
export type MetricValue = Schemas["MetricValue"];
export type ErrorInfo = Schemas["ErrorInfo"];
export type FetchError = Schemas["FetchError"];
export type AggregatorHealth = Schemas["AggregatorHealth"];
export type Location = Schemas["Location"];
export type Tile = Schemas["Tile"];

// ---------------------------------------------------------------------
// Hand-curated camera + plug shapes (mirror lab_skills/registry.py and
// kasa_tapo_services/models.py).
// ---------------------------------------------------------------------

export interface CameraLens {
  id: string;
  label: string;
  rtsp_path: string;
  /** False for fixed lenses that have no PTZ motor (e.g. wide on C245D). Defaults to true. */
  ptz_capable?: boolean;
}

export interface CameraConfig {
  host: string;
  onvif_port?: number;
  rtsp_port?: number;
  lenses: CameraLens[];
}

export interface PlugOutletConfig {
  index: number;
  label?: string | null;
}

export interface PlugConfig {
  host: string;
  outlets?: PlugOutletConfig[];
}

export interface PresetEntry {
  id: string;
  name: string;
}

export interface LensStatusEntry {
  id: string;
  label: string;
  rtsp_path: string;
  mse_url?: string | null;
  stream_connected?: boolean | null;
  recording_active?: boolean;
  recording_started_at?: string | null;
  rolling_active?: boolean;
  rolling_started_at?: string | null;
  rolling_segment_count?: number;
}

/** Shape of `EquipmentStatus.details` for `kind: camera`. */
export interface CameraDetails {
  lenses: LensStatusEntry[];
  presets: PresetEntry[];
  privacy_mode?: boolean;
  streaming_enabled?: boolean;
  onvif_reachable?: boolean;
  tapo_reachable?: boolean;
  go2rtc_reachable?: boolean;
}

// ---------------------------------------------------------------------
// EquipmentSnapshot + EquipmentList: re-typed to widen `kind` to the
// extended literal, attach the registry blocks, and replace `details`
// with `Record<string, unknown>` (the auto-generated type uses `never`).
// ---------------------------------------------------------------------

export type EquipmentStatus = Omit<
  Schemas["EquipmentStatus"],
  "equipment_kind" | "details"
> & {
  equipment_kind: EquipmentKind;
  details?: Record<string, unknown> & Partial<CameraDetails>;
};

export type EquipmentSnapshot = Omit<
  Schemas["EquipmentSnapshot"],
  "kind" | "status"
> & {
  kind: EquipmentKind;
  status: EquipmentStatus;
  camera?: CameraConfig | null;
  plug?: PlugConfig | null;
};

export interface EquipmentList {
  equipment: EquipmentSnapshot[];
  fetched_at: string;
}

// ---------------------------------------------------------------------
// Control request bodies (mirror kasa_tapo_services.models).
// ---------------------------------------------------------------------

export type PtzDirection =
  | "up"
  | "down"
  | "left"
  | "right"
  | "up_left"
  | "up_right"
  | "down_left"
  | "down_right"
  | "stop";

export interface PtzNudgeRequest {
  direction: PtzDirection;
  speed?: number;
  duration_ms?: number;
}

export interface PtzContinuousRequest {
  pan?: number;
  tilt?: number;
  zoom?: number;
  duration_ms?: number | null;
}

export interface PresetSaveRequest {
  name: string;
}

export interface PresetGotoRequest {
  preset_id: string;
}

export interface PrivacyRequest {
  enabled: boolean;
}

export interface StreamingRequest {
  enabled: boolean;
}

export interface PlugSwitchRequest {
  outlet?: number | null;
}

export interface ControlAck {
  ok?: boolean;
  message?: string | null;
  state?: Record<string, unknown> | null;
}

// ---------------------------------------------------------------------
// Snapshot + recording (mirrors kasa_tapo_services.models).
// ---------------------------------------------------------------------

export interface SnapshotRequest {
  lens?: string | null;
}

export interface SnapshotResponse {
  path: string;
  url: string;
  taken_at: string;
  lens: string;
  width?: number | null;
  height?: number | null;
  bytes?: number | null;
}

export interface RecordingStartRequest {
  lens?: string | null;
  max_duration_s?: number | null;
}

export interface RecordingStartResponse {
  recording_id: string;
  path: string;
  url: string;
  lens: string;
  started_at: string;
  max_duration_s?: number | null;
}

export interface RecordingStopRequest {
  recording_id?: string | null;
}

export interface RecordingStopResponse {
  recording_id: string;
  path: string;
  url: string;
  started_at: string;
  stopped_at: string;
  duration_ms: number;
  bytes?: number | null;
  finalized: boolean;
}

export interface RecordingCancelRequest {
  recording_id?: string | null;
}

export interface RecordingCancelResponse {
  recording_id: string;
  canceled: boolean;
  deleted_path?: string | null;
}

export interface RollingStartRequest {
  lens?: string | null;
  segment_duration_s?: number;
  max_segments?: number;
  include_audio?: boolean;
}

export interface RollingStopResponse {
  ok: boolean;
  message?: string | null;
  segments_recorded: number;
}

export interface MediaFile {
  name: string;
  lens: string;
  kind: "snapshots" | "recordings";
  bytes: number;
  mtime: string;
  url: string;
  abs_path: string;
}

export interface MediaListing {
  snapshots: MediaFile[];
  recordings: MediaFile[];
}
