/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Equipment
         * @description Return the latest status of every registered equipment in parallel.
         */
        get: operations["list_equipment_api_equipment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/equipment/{equipment_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Equipment
         * @description Live status fetch for a single equipment.
         */
        get: operations["get_equipment_api_equipment__equipment_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AggregatorHealth */
        AggregatorHealth: {
            /**
             * Status
             * @default healthy
             * @constant
             */
            status: "healthy";
            /** Version */
            version: string;
            /** Equipment Count */
            equipment_count: number;
        };
        /** ComponentStatus */
        ComponentStatus: {
            /** Connected */
            connected: boolean;
            /** State */
            state: string;
            /** Message */
            message?: string | null;
            /** Last Event At */
            last_event_at?: string | null;
        };
        /** EquipmentList */
        EquipmentList: {
            /** Equipment */
            equipment: components["schemas"]["EquipmentSnapshot"][];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /**
         * EquipmentSnapshot
         * @description What the dashboard frontend consumes for one equipment.
         *
         *     Wraps `EquipmentStatus` with aggregator-side metadata (when we last fetched
         *     it, how long it took, and whether the latest fetch errored). The `status`
         *     field is always present - on first failure the aggregator emits a synthetic
         *     `unknown` envelope so the UI never has to deal with `null`.
         */
        EquipmentSnapshot: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Platform */
            platform: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "solid_doser" | "liquid_handler" | "press" | "fume_hood" | "robot_arm" | "environmental_sensor" | "hplc" | "plate_reader" | "plate_sealer" | "plate_stacker" | "other";
            /** Adapter */
            adapter: string;
            status: components["schemas"]["EquipmentStatus"];
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /** Latency Ms */
            latency_ms?: number | null;
            fetch_error?: components["schemas"]["FetchError"] | null;
            /** Base Url */
            base_url?: string | null;
            location?: components["schemas"]["Location"] | null;
            tile?: components["schemas"]["Tile"];
        };
        /**
         * EquipmentStatus
         * @description Unified equipment status envelope (spec v1.0).
         */
        EquipmentStatus: {
            /**
             * Protocol Version
             * @default 1.0
             */
            protocol_version: string;
            /** Equipment Id */
            equipment_id: string;
            /** Equipment Name */
            equipment_name: string;
            /**
             * Equipment Kind
             * @enum {string}
             */
            equipment_kind: "solid_doser" | "liquid_handler" | "press" | "fume_hood" | "robot_arm" | "environmental_sensor" | "hplc" | "plate_reader" | "plate_sealer" | "plate_stacker" | "other";
            /** Equipment Version */
            equipment_version?: string | null;
            /** Host */
            host?: string | null;
            /**
             * Equipment Status
             * @enum {string}
             */
            equipment_status: "ready" | "busy" | "requires_init" | "degraded" | "dry_run" | "error" | "e_stop" | "unknown";
            /** Message */
            message?: string | null;
            /** Required Actions */
            required_actions?: string[];
            /**
             * Device Time
             * Format: date-time
             */
            device_time: string;
            /** Uptime Seconds */
            uptime_seconds?: number | null;
            /** Components */
            components?: {
                [key: string]: components["schemas"]["ComponentStatus"];
            };
            /** Metrics */
            metrics?: {
                [key: string]: components["schemas"]["MetricValue"];
            };
            last_error?: components["schemas"]["ErrorInfo"] | null;
            /** Details */
            details?: {
                [key: string]: unknown;
            };
        };
        /** ErrorInfo */
        ErrorInfo: {
            /** Code */
            code?: string | null;
            /** Message */
            message: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "info" | "warning" | "error" | "critical";
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
        };
        /**
         * FetchError
         * @description Set by the aggregator when an adapter fails to fetch a fresh status.
         */
        FetchError: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "timeout" | "connection_refused" | "http_4xx" | "http_5xx" | "parse_error" | "unconfigured" | "unknown";
            /** Message */
            message: string;
            /** Http Status */
            http_status?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Location
         * @description Position of an equipment on the lab floorplan map (percentages 0-100).
         */
        Location: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Label */
            label?: string | null;
        };
        /** MetricValue */
        MetricValue: {
            /** Value */
            value: number | string | boolean;
            /** Unit */
            unit?: string | null;
            /** Timestamp */
            timestamp?: string | null;
        };
        /**
         * Tile
         * @description Tile size for the dashboard equipment grid.
         *
         *     The platform card lays equipment out on a 4-column CSS grid with fixed-height
         *     rows. `w` is the number of columns the tile spans (1..4) and `h` is the
         *     number of rows it spans (1..4). Default 2x1 = current half-row layout.
         */
        Tile: {
            /**
             * W
             * @default 2
             */
            w: number;
            /**
             * H
             * @default 1
             */
            h: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregatorHealth"];
                };
            };
        };
    };
    list_equipment_api_equipment_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentList"];
                };
            };
        };
    };
    get_equipment_api_equipment__equipment_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                equipment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
