/**
 * Curated re-exports of dashboard API types.
 *
 * The full path/operation surface is at `./api.generated.ts`, regenerated by
 * `npm run gen:api-types` against the live FastAPI OpenAPI document. This file
 * keeps the names short and is the only thing app code should import.
 */

import type { components } from "./api.generated";

type Schemas = components["schemas"];

export type EquipmentKind = NonNullable<Schemas["EquipmentSnapshot"]["kind"]>;
export type EquipmentState = Schemas["EquipmentStatus"]["equipment_status"];
export type ErrorSeverity = Schemas["ErrorInfo"]["severity"];
export type FetchErrorKind = Schemas["FetchError"]["kind"];

export type ComponentStatus = Schemas["ComponentStatus"];
export type MetricValue = Schemas["MetricValue"];
export type ErrorInfo = Schemas["ErrorInfo"];
export type EquipmentStatus = Schemas["EquipmentStatus"];
export type FetchError = Schemas["FetchError"];
export type EquipmentSnapshot = Schemas["EquipmentSnapshot"];
export type EquipmentList = Schemas["EquipmentList"];
export type AggregatorHealth = Schemas["AggregatorHealth"];
export type Location = Schemas["Location"];
export type Tile = Schemas["Tile"];
