"""The lineage seam, against a package bitácora's compiler actually produced.

Every other test in `test_lineage.py` feeds the derivation a package *this*
repo wrote, which pins our own behaviour and nothing about the other side of
the seam. The two repos agree on a shape neither of them owns — the compiler
emits it, the executor verifies and consumes it — so a hand-written fixture can
stay green through a rename on the far side and the drift only surfaces on a
bench run.

So the fixture here was **generated by running bitácora's compiler**
(`compile_protocol`, compiler 0.6.0 at commit b060cd5) and vendored verbatim,
provenance and all, exactly as the authorization route publishes it:
`{**package.digest_payload(), "warnings": warnings}`. Regenerating it is a
deliberate act with a recorded date, which is the point — if the compiler's
shape moves, this file has to be rebuilt and the diff says what moved.

What it pins, in order of what would hurt most to get wrong: the executor's
digest verifier accepts a real 0.6.0 package (`lineage` and `substances`
included — both were once absent from the hashed set, and the failure mode is a
false tamper report that refuses a legitimate run); a lineage entry's key set;
and that the derivation turns the whole thing into transfer specs, amounts and
all.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from app.lineage import transfers_from
from app.workflow import (
    Authorization,
    RunRefused,
    digest_payload_of,
    plan_from,
    verify_package_digest,
)

FIXTURE = Path(__file__).parent / "fixtures" / "lineage_package_compiler_0_6_0.json"

#: The six keys `compile.lineage_of` emits per (source plate, destination well).
#: `hid` is *omitted* rather than null on an unbound plate, which is why
#: `app.lineage` reads both ends with `.get`.
LINEAGE_KEYS = {"step_id", "mapping", "source", "source_well", "dest", "dest_well"}


def _fixture() -> tuple[dict, dict]:
    raw = json.loads(FIXTURE.read_text())
    return raw["package"], raw["_provenance"]


def _authorization(package: dict, provenance: dict) -> Authorization:
    """The authorization the runner would have pulled, carrying this package."""
    return Authorization(
        authorization_id="ra_fixture", project_id="chanlam",
        protocol_path="protocols/lineage_fixture.yaml", commit_sha="deadbee",
        package_digest=provenance["package_digest"], package=package,
        binding={"liquid_handler": "ot2_hte"}, authorized_by="op@lab",
        executable=True, revoked_at=None, expires_at="2099-01-01T00:00:00Z",
        plate_bindings=provenance["plate_bindings"],
    )


def test_the_fixture_says_where_it_came_from() -> None:
    """A vendored artifact with no provenance is indistinguishable from one
    somebody typed. The recorded version must also be the one inside."""
    package, provenance = _fixture()
    assert provenance["generated_by"] == "bitacora compile_protocol"
    assert provenance["compiler_version"] == package["compiler_version"] == "0.6.0"
    assert provenance["commit"] and provenance["date"]


def test_a_real_package_verifies_against_the_digest_bitacora_published() -> None:
    """The whole point of the verifier: recompute from the published package
    alone and get the issuer's number back. A check only the issuer can perform
    is not a check."""
    package, provenance = _fixture()
    verify_package_digest(_authorization(package, provenance))  # does not raise


def test_lineage_and_substances_are_inside_the_hash() -> None:
    """Each optional digest field arrived as a false tamper report waiting to
    happen: bitácora starts hashing a new field, the executor does not, and a
    legitimate package reads as edited. Mutating each one here must change the
    recomputed digest — that is what says it is covered."""
    package, provenance = _fixture()
    for field in ("lineage", "substances", "plates"):
        assert package[field], f"the fixture must exercise {field}"
        edited = {**package, field: {"tampered": True}}
        with pytest.raises(RunRefused, match="digest mismatch"):
            verify_package_digest(_authorization(edited, provenance))


def test_warnings_ride_along_but_are_not_hashed() -> None:
    """`warnings` is compiler commentary, not what would run — it is published
    inside the package and deliberately outside the payload."""
    package, provenance = _fixture()
    assert "warnings" in package
    assert "warnings" not in digest_payload_of(package)
    verify_package_digest(_authorization({**package, "warnings": ["late note"]},
                                         provenance))  # still verifies


def test_every_lineage_entry_carries_exactly_the_compilers_keys() -> None:
    """One entry per (source plate, destination well), and both ends resolved to
    a bound `hid` — which is what lets the executor point a ledger row at real
    containers without re-deriving anybody's mapping semantics."""
    package, _ = _fixture()
    entries = package["lineage"]
    assert len(entries) == 2
    for entry in entries:
        assert set(entry) == LINEAGE_KEYS
        assert set(entry["source"]) == set(entry["dest"]) == {"plate", "hid"}
        assert entry["mapping"] == "identity"
        assert entry["step_id"] == "transfer_acid"   # the protocol step, not a compiled one
    assert {e["dest_well"] for e in entries} == {"A1", "B1"}


def test_the_package_is_also_an_executable_plan() -> None:
    """A per-well action expands to `{step}__{well}__{sub}`, which is the id
    shape `gating_steps` narrows on. If this ever stopped holding, the gate
    would silently widen from one well to all of them."""
    package, provenance = _fixture()
    plan = plan_from(_authorization(package, provenance))
    assert [s.id for s in plan.steps][:2] == ["transfer_acid__A1__tip",
                                             "transfer_acid__A1__aspirate"]
    assert len(plan.steps) == 8


def test_the_real_package_derives_transfer_specs_with_their_volumes() -> None:
    """End to end over the seam: compiler output in, ledger-shaped specs out.
    The amount comes from the dispense step's own `volume_ul`, so this also
    pins that the compiler still resolves that placeholder to a *number* — a
    string would silently drop the amount rather than fail."""
    package, _ = _fixture()
    statuses = {s["step_id"]: "succeeded" for s in package["steps"]}
    specs = transfers_from(package, statuses)

    assert len(specs) == 2
    assert [(s["source_hid"], s["source_well"], s["dest_hid"], s["dest_well"])
            for s in specs] == [("PLT-0007", "A1", "PLT-0042", "A1"),
                                ("PLT-0007", "B1", "PLT-0042", "B1")]
    assert all(s["step_id"] == "transfer_acid" for s in specs)
    assert all((s["amount_commanded"], s["unit"]) == (50.0, "uL") for s in specs)
    # The gate narrowed to this well's own four sub-steps, not all eight.
    assert specs[0]["gated_by"] == ["transfer_acid__A1__tip", "transfer_acid__A1__aspirate",
                                    "transfer_acid__A1__dispense", "transfer_acid__A1__drop"]


def test_one_failed_well_in_the_real_package_suppresses_only_its_own_row() -> None:
    package, _ = _fixture()
    statuses = {s["step_id"]: "succeeded" for s in package["steps"]}
    statuses["transfer_acid__B1__dispense"] = "failed"
    assert [s["dest_well"] for s in transfers_from(package, statuses)] == ["A1"]
